# # -- 09:05 ~

# with T as (
# select SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
# from OFFLINE_SALE
# union all
# select SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
# from ONLINE_SALE
# )

# select *
# from T
# where date_format(SALES_DATE, '%Y-%m') = '2022-03'
# order by 1, 2, 3
-- MYSQL
(SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE 
WHERE DATE_FORMAT(SALES_DATE, '%m') = '03')
UNION ALL
(SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%m') = '03')
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;